# Generated by Django 3.1 on 2020-08-25 00:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leemon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('nit', models.IntegerField()),
                ('card_number', models.IntegerField()),
                ('card_exp', models.DateTimeField()),
                ('address', models.CharField(max_length=200)),
                ('text_image', models.TextField()),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.AlterModelTable(
            name='category',
            table='employee',
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leemon.customers')),
            ],
            options={
                'db_table': 'purchases',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT VALUE', max_length=200)),
                ('description', models.TextField()),
                ('value', models.IntegerField()),
                ('id_discount', models.IntegerField()),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leemon.category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.AddField(
            model_name='customers',
            name='id_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leemon.image'),
        ),
    ]
