# Generated by Django 3.1 on 2020-08-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leemon', '0002_auto_20200825_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
