# Generated by Django 3.1 on 2020-08-25 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leemon', '0005_auto_20200825_0134'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
