# Generated by Django 3.1 on 2020-08-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leemon', '0006_auto_20200825_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='card_exp',
            field=models.CharField(max_length=10),
        ),
    ]
