# Generated by Django 3.1 on 2020-08-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leemon', '0009_auto_20200825_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='text_image',
            field=models.TextField(default='None'),
        ),
    ]
