# Generated by Django 3.1 on 2020-08-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leemon', '0012_auto_20200825_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='card_number',
            field=models.CharField(max_length=20),
        ),
    ]
